package by.epam.tc.conference.dao.mysql.pool;

import java.sql.PreparedStatement;
import java.sql.SQLException;

public interface Connector {

    PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException, ConnectionPoolException;

    PreparedStatement prepareStatement(String sql) throws SQLException, ConnectionPoolException;

    void startTransaction() throws SQLException, ConnectionPoolException;

    void commitTransaction() throws SQLException;

    void rollback() throws SQLException;

    void closeConnection();
}
